modLoader="javafml"
loaderVersion="[38,)"
license="MIT License"
issueTrackerURL="https://github.com/EwyBoy/SeedDrop"
credits="Quarris for helping me fix shit"
authors="Ewy"

[[mods]]
modId="seeddrop"
version="${file.jarVersion}"
displayName="Seed Drop"
description="Customize seed loot tables"

[[dependencies.seeddrop]]
modId="forge"
mandatory=true
versionRange="[38,)"
ordering="NONE"
side="BOTH"

[[dependencies.seeddrop]]
modId="minecraft"
mandatory=true
versionRange="[1.18, 1.19)"
ordering="NONE"
side="BOTH"