modLoader="javafml"
loaderVersion="[46,)"
license="MIT License"
issueTrackerURL="https://github.com/EwyBoy/SeedDrop"
credits=""
authors="Ewy"

[[mods]]
modId="seeddrop"
version="${file.jarVersion}"
displayName="Seed Drop"
description="Customize seed loot tables"

[[dependencies.seeddrop]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"

[[dependencies.seeddrop]]
modId="minecraft"
mandatory=true
versionRange="[1.20, 1.21)"
ordering="NONE"
side="BOTH"